language: generic
sudo: required
dist: trusty
services:
- docker
matrix:
  include:
  - env: ARCH=x86_64 ARCH_CMD=linux64
    os: linux
  - os: osx
before_install: bin/ci prepare_system
install: bin/ci prepare_build
script:
- bin/ci with_build_env 'make'
after_success:
- mv ./biplane biplane-$TRAVIS_OS_NAME
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wgl5GrwXl6jLcW6Vpb1DIJAdZpHHloHzzFJMcLJ49aGRz7VzAyFf+TfQhliJ1Xnw7et4pWo5fHty1wdh7Br9u1TUsgGeBG1ljMOSL6xJPjP0US7NXyJoUUpWHfCoZcpSyzCZpvdWYtBtn4hFeeMnvPEsQuwUIt5UIx/GQUST8Ud8nddn9BudSLpU1esJQZUA5pIbM5mMndPgJj/QfGk0yZrZcVWibaJJ2F1Er8jqHSEf0WjLVrHTcQIjWx6UiD3zmyA5bRPSFikxl+xUODvOA+t9dSP50L/WVoiRGWgphttCc/M+4gF7o5iPuIzzFM7lPEF3j2SJGo22lQE/wS+bXviHOXz0ef6ByTC7YwsUW2k39NM1o0mOMWD0qPjaVAnaJix2ViTgZ0jgCA55qZ9RBEAErVMNmzleR2T8FsUtq1yKbAhj307CP6fnN0n4Lttm3rp+D238CPJ19K5YbK6xkWmadgpw7sBR/M5jSgWbxm2yQxzFkbM2zATPSyJEpf563fhvMQT4tyyuPb+BY93y1MCGyMpaxbf1O32nRK8lwyb+6HfJmdu5w+fW8T+SzsOvjLddrJrriY6eoyL55IqmoDCBtfcT9fjh9t/UIaN5oxHwvzex5nlzcuy2ph6qU5Ru4XA+6wlgdbPxKuau12TDEnaimWdLJgAC0SeX+/kwp0Q=
  file: 
    - biplane-$TRAVIS_OS_NAME
  on:
    tags: true
notifications:
  slack:
    secure: VI1gD1I8chUxWLQUAPm+Iea5U7wm/6Gzf6KOAtN9/NcnhaXSkIKFvPe7bm3GPXVSnJmpGcK6bIEblybm35p2QpfXnyQYYNf0GKGRrwDL7k9g0XKcjNshO2TM7D0ZVNYQTs0leGypQU4PdS0xhg3SkIigz6UcLeadBIp8OXQ3U/Afh72i2r0x3UgYJ4xkiBwEdKiZ38o4OuJtVcWmBPMv/clEIj5JUkoSCV4JL5K1Ij16Iu8KLWAhHOvjyRmC8NHvX754hf6ZygJlCNdyAqxwmr8NHh2bn2ujwbcBl8z+eS6XorEesgtSgxTgkiUqKnHvxAP2/gzRMLmEEoKpVu/68OvOstnwtqClelj9tBtzRp1uaylhacM1sw3rmbrEjl7dQRPzt50yzb6T+H/YPcnYcOAHPEGT6wuVgKeyVCWmHaHxgu75Tf6nWc0RI7dyKphkVGjGueoB/opsfxeN9itRwQCHujQ0nu1wsNQa8n/Ersd5Q6cGXctvQ+w+XYY1b+/reIwnIy0/ty5bkYAkZC3bS5p7Suxo6QFicuysqaHlylXoa1xV97w7rYCF2xpJYQSPfB5SvQqkOIvmLNkNqIQ8WQ3YeIviKOx0hdJ9f6ysye9+G1EnvlpRjpafEtFWu/UBJqM+3kx2yUYiq0pQ/M+u2VleU3iCa+KV2de9oBjGoIQ=

